#=================================================
# https://github.com/HandsomeYingyan/HandsomeMod-ci
# Description: Build HandsomeMod using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build HandsomeMod

on:
  repository_dispatch:
    types: helloworld
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
 # watch:
   # types: started
   workflow_dispatch:

env:
  REPO_URL: https://github.com/HandsomeMod/HandsomeMod
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Check Server Performance
      run: |
        echo "Warning⚠"
        echo "The allocated server performance is limited. If too many plugins are selected, be sure to pay attention to CPU performance！"
        echo -e "CPU models（descending）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU information--------------------------"
        echo "CPU physical number：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU core information：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------Memory information--------------------------"
        echo "Installed memory details："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------Disk information--------------------------"
        echo "Disk quantity：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Cleanup Disk
      uses: Santuybe/cleanup-disk-action@v3.0
          
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig python3-dev python-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
 
    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH handsomemod
      
    - name: Update feeds
      run: cd handsomemod && ./scripts/feeds update -a

    - name: Install feeds
      run: cd handsomemod && ./scripts/feeds install -a 

    - name: Download package
      id: package
      run: |
        cd handsomemod
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd handsomemod
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: env.UPLOAD_BIN_DIR == 'true'
      with:
        name: HandsomeMod_bin
        path: handsomemod/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd handsomemod/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: HandsomeMod_firmware
        path: ${{ env.FIRMWARE }}
